2025-01-05 20:59:39,924 - Loading cached SSO token for jobtestprep
2025-01-05 20:59:40,693 - SSO token refresh attempt failed
Traceback (most recent call last):
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 297, in _refresh_access_token
    return self._attempt_create_token(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 256, in _attempt_create_token
    response = self._client.create_token(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidGrantException: An error occurred (InvalidGrantException) when calling the CreateToken operation: 
2025-01-05 20:59:40,737 - Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 538, in _protected_refresh
    metadata = self._refresh_using()
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 685, in fetch_credentials
    return self._get_cached_credentials()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 695, in _get_cached_credentials
    response = self._get_credentials()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 2150, in _get_credentials
    token = initial_token_data.get_frozen_token().token
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 82, in get_frozen_token
    self._refresh()
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 95, in _refresh
    self._protected_refresh()
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 122, in _protected_refresh
    raise TokenRetrievalError(
botocore.exceptions.TokenRetrievalError: Error when retrieving token from sso: Token has expired and refresh failed
2025-01-05 21:00:01,460 - Loading cached SSO token for jobtestprep
2025-01-05 21:00:01,890 - SSO token refresh attempt failed
Traceback (most recent call last):
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 297, in _refresh_access_token
    return self._attempt_create_token(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 256, in _attempt_create_token
    response = self._client.create_token(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidGrantException: An error occurred (InvalidGrantException) when calling the CreateToken operation: 
2025-01-05 21:00:01,891 - Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 538, in _protected_refresh
    metadata = self._refresh_using()
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 685, in fetch_credentials
    return self._get_cached_credentials()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 695, in _get_cached_credentials
    response = self._get_credentials()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 2150, in _get_credentials
    token = initial_token_data.get_frozen_token().token
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 82, in get_frozen_token
    self._refresh()
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 95, in _refresh
    self._protected_refresh()
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 122, in _protected_refresh
    raise TokenRetrievalError(
botocore.exceptions.TokenRetrievalError: Error when retrieving token from sso: Token has expired and refresh failed
2025-01-05 21:00:41,451 - Loading cached SSO token for jobtestprep
2025-01-05 21:00:41,916 - SSO token refresh attempt failed
Traceback (most recent call last):
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 297, in _refresh_access_token
    return self._attempt_create_token(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 256, in _attempt_create_token
    response = self._client.create_token(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidGrantException: An error occurred (InvalidGrantException) when calling the CreateToken operation: 
2025-01-05 21:00:41,932 - Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 538, in _protected_refresh
    metadata = self._refresh_using()
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 685, in fetch_credentials
    return self._get_cached_credentials()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 695, in _get_cached_credentials
    response = self._get_credentials()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\credentials.py", line 2150, in _get_credentials
    token = initial_token_data.get_frozen_token().token
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 82, in get_frozen_token
    self._refresh()
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 95, in _refresh
    self._protected_refresh()
  File "C:\Users\HadarNeulander\.vscode\Repos\DevSecOps-Pyhton\devvenv\Lib\site-packages\botocore\tokens.py", line 122, in _protected_refresh
    raise TokenRetrievalError(
botocore.exceptions.TokenRetrievalError: Error when retrieving token from sso: Token has expired and refresh failed
2025-01-05 21:02:09,373 - Loading cached SSO token for jobtestprep
2025-01-05 21:02:11,323 - Starting SQS policy scan
2025-01-05 21:02:11,849 - Scanning region: ap-south-1
2025-01-05 21:02:15,110 - Scanning region: eu-north-1
2025-01-05 21:02:18,702 - Scanning region: eu-west-3
2025-01-05 21:02:21,869 - Scanning region: eu-west-2
2025-01-05 21:02:23,611 - Scanning region: eu-west-1
2025-01-05 21:02:24,428 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/candidate-api-ai-hub-dlq-dev: 'Attributes'
2025-01-05 21:02:24,837 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/candidate-api-ai-hub-sqs-dev: 'Attributes'
2025-01-05 21:02:25,451 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/candidate-api-candidate-api-dlq-dev: 'Attributes'
2025-01-05 21:02:26,285 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/candidate-api-recruiter-api-dlq-dev: 'Attributes'
2025-01-05 21:02:27,192 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/candidate-api-test-system-dlq-dev: 'Attributes'
2025-01-05 21:02:28,012 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/delete-expired-cognito-users-dlq-dev: 'Attributes'
2025-01-05 21:02:28,832 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/delete-expired-database-users-dlq-dev: 'Attributes'
2025-01-05 21:02:29,753 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/ms-reviews-yotpo-order-dlq-dev: 'Attributes'
2025-01-05 21:02:30,877 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/ms-reviews-yotpo-product-dlq-dev: 'Attributes'
2025-01-05 21:02:31,698 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/notification-system-email-status-dlq-dev: 'Attributes'
2025-01-05 21:02:32,516 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/notification-system-shared-dlq-dev: 'Attributes'
2025-01-05 21:02:33,336 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/recruiter-api-candidate-api-dlq-dev: 'Attributes'
2025-01-05 21:02:34,155 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/recruiter-api-recruiter-api-dlq-dev: 'Attributes'
2025-01-05 21:02:34,973 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/recruiter-api-user-management-dlq-dev: 'Attributes'
2025-01-05 21:02:36,005 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/users-management-ms-events-dlq-dev.fifo: 'Attributes'
2025-01-05 21:02:36,825 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/users-management-recruiter-api-dlq-dev: 'Attributes'
2025-01-05 21:02:37,637 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/users-management-reporting-users-management-dlq-dev: 'Attributes'
2025-01-05 21:02:38,456 - Error processing queue https://sqs.eu-west-1.amazonaws.com/377727784153/users-management-users-management-api-ns-dlq-dev: 'Attributes'
2025-01-05 21:02:38,868 - Scanning region: ap-northeast-3
2025-01-05 21:02:41,836 - Scanning region: ap-northeast-2
2025-01-05 21:02:43,371 - Scanning region: ap-northeast-1
2025-01-05 21:02:54,755 - Scanning region: ca-central-1
2025-01-05 21:02:55,660 - Scanning region: sa-east-1
2025-01-05 21:02:56,991 - Scanning region: ap-southeast-1
2025-01-05 21:03:02,933 - Scanning region: ap-southeast-2
2025-01-05 21:03:07,025 - Scanning region: eu-central-1
2025-01-05 21:03:07,436 - Scanning region: us-east-1
2025-01-05 21:03:08,973 - External access found in queue: test-sqs (Region: us-east-1)
2025-01-05 21:03:09,173 - Policy updated for queue: test-sqs
2025-01-05 21:03:09,176 - Scanning region: us-east-2
2025-01-05 21:03:11,123 - Scanning region: us-west-1
2025-01-05 21:03:12,454 - Scanning region: us-west-2
2025-01-05 21:03:15,729 - Log file uploaded to s3://s3-sqs-modifier-test-bucket/sqs_policy_scan_20250105_210314.log
2025-01-05 21:03:15,732 - Scan complete
